config/routes.rb
Rails.application.routes.draw do
  get 'home/show'
  get 'auth/:provider/callback', to: 'sessions#create', as: 'signin'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  delete 'stocks/:id', to: 'stocks#destroy', as: 'stocks'
  get 'stock/:id', to: 'stocks#show'
  get 'bitcoin', to: 'stocks#bitcoin'
  get 'historical/:id', to: 'stocks#history'
  get 'stocks/:query', to: 'stocks#index'
  get 'stocks/:id/add', to: 'stocks#create', as: 'add'
  get 'users/stocktwits', to: 'users#refreshst'
  get 'users/portfolio', to:'users#show_portfolio', as: 'show_portfolio'
  get 'users/edit_portfolio', to:'users#edit_portfolio', as: 'edit_portfolio'
  root to: "home#show"

end

app/models/seed.rb
require 'csv'
require 'net/http'

class Seed

  def get_logo_urls
    l = []
    CSV.foreach('db/companylist.csv') do |row|
      url_str = %{http://content.nasdaq.com/logos/#{row[0]}.gif}
      response = Net::HTTP.get_response(URI(url_str))
      l << %{Stock.find_by(ticker: "#{row[0]}").update(logo: #{url_str})} if response.kind_of?(Net::HTTPSuccess)
    end
    l
  end

  def generate_data
    d = []
    CSV.foreach('db/companylist.csv') do |row|
      d << %{Stock.create(ticker: "#{row[0]}", name: "#{row[1]}", sector: "#{row[6]}", industry: "#{row[7]}")}
    end
    d
  end

  def write_basic_data
    File.open('db/seeds.rb', 'w+') do |f|
      f.puts generate_data
    end
  end

  def write_logo_data
    File.open('db/seeds-logos.rb', 'w+') do |f|
      f.puts get_logo_urls
    end
  end

end

#Seed.new.write_basic_data
Seed.new.write_logo_data

app/models/stock.rb
# Stock
class Stock < ActiveRecord::Base
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :ticker, :name, presence: true

end

app/models/user.rb
require 'json'
require 'net/http'
require 'open-uri'

# User
class User < ActiveRecord::Base
  has_many :user_stocks
  has_many :stocks, through: :user_stocks

  validates :name, presence: true

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.profile_pic = auth.info.image
      user.save!
    end
  end

  def stocktwits_urls
    urls = []
    self.stocks.each do |s|
      urls << "http://stocktwits.com/symbol/#{s.ticker}"
    end
    urls
  end

  def visit_urls
    messages = []
    stocktwits_urls.each do |url|
      doc = Nokogiri::HTML(open(url))
      doc.xpath('//ol/li').each do |item|
        messages << item.values
      end
    end
    messages
  end

  def stocktwits_feed
    msgs = []
    visit_urls.each do |m|
      message = {}
      full_message = JSON.parse(m[0])
      message[:time] = Time.parse(full_message["created_at"])
      message[:avatar] = full_message["avatar_url"]
      message[:body] = full_message["body"]
      message[:user] = full_message["user"]["username"]
      msgs << message
    end
    msgs.uniq.sort_by{|hsh| hsh[:time]}.reverse!
  end

  def get_price
    quotes = YahooFinance.quotes(self.stocks.pluck(:ticker).reverse, [:ask])
  end

  def portfolio_show
    @stocks = UserStock.where(user_id: self.id).reverse
  end

  def self.by_letter(letter)
    where('name LIKE ?', "#{letter}%").order(:name)
  end
end

app/models/user_stock.rb
# UserStock
class UserStock < ActiveRecord::Base
  belongs_to :user
  belongs_to :stock
  validates_uniqueness_of :stock_id, :scope => :user_id
end

app/controllers/application_controller.rb
# ApplicationController
class ApplicationController < ActionController::Base
  helper_method :current_user
  protect_from_forgery except: :show
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    if @current_user && @current_user.stocks.count == 0
      @current_user.stocks << Stock.find_by(ticker: 'AAPL')
    end
    @current_user
  end
end

app/controllers/home_controller.rb
# Home Controller
class HomeController < ApplicationController
  def show
    render 'login' unless current_user
  end
end

app/controllers/sessions_controller.rb
# Sessions Controller
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/stocks_controller.rb
require 'csv'
# Stocks Controller
class StocksController < ApplicationController
  def index
    @stocks = Stock.where('UPPER(name) LIKE UPPER(?) OR UPPER(ticker) LIKE UPPER(?)',
                          "#{params[:query]}%", "#{params[:query]}%")
    @user_stocks = current_user.stocks
    respond_to do |format|
      format.json { render json: { stock: @stocks[0..9], stocks: @user_stocks } }
    end
  end

  def show
    @stock = Stock.find(params[:id])
    respond_to do |format|
      format.json { render json: @stock }
    end
  end

  def bitcoin
    @bitcoin = JSON.load(open('https://www.bitstamp.net/api/ticker/'))
    respond_to do |format|
      format.json { render json: @bitcoin }
    end
  end

  def history
    @history = []
      url = "http://ichart.yahoo.com/table.csv?s=#{params[:id]}&a=6&b=1&c=2014&d=7&e=30&f=2014&g=d&ignore=.csv"
      CSV.new(open(url), :headers => :first_row).each do |line|
        data = []
        data << line[0].gsub('-','').to_i
        data <<  line[4].to_i
        @history << data
      end
    respond_to do |format|
      format.json { render json: @history.reverse }
    end
  end

  def create
    @stock = Stock.find(params[:id])
    current_user.stocks << @stock
    respond_to do |format|
      format.json { render json: @stock }
    end
  end

  def destroy
    @stock = Stock.find(params[:id])
    current_user.stocks.delete(@stock)
    respond_to do |format|
      format.js
    end
  end

  private

  def stock_params
    params.require(:stock).permit(:query, :id)
  end
end

app/controllers/user_stocks_conroller.rb
class UserStocksController < ApplicationController

	def create
  	binding.pry
  	#add stock to user's watchlist
  	@stock = Stock.find_by(name: params[:name])
  	@user_stock = UserStock.create(stock_id: @stock.id, user_id: current_user.id)
  	# @stock = Stock.find_by(name: params[:name])
  	# current_user.stocks << @stock
  	respond_to do |format|
  		format.js
  	end
  end

end

app/controllers/user_stocks_controller.rb
# UserStocksController
class UserStocksController < ApplicationController
	def create
		@stock = Stock.find_by(name: params[:name])
		@user_stock = UserStock.create(stock_id: @stock.id, user_id: current_user.id)
		respond_to do |format|
			format.js
		end
	end
end

app/controllers/users_controller.rb
# Users Controller
class UsersController < ApplicationController
  def refreshst
    render :partial => 'partials/sidebar'
  end

  def edit_portfolio
    render :partial => 'partials/portfolioEdit'
  end

  def show_portfolio
    render :partial => 'partials/portfolio'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/login.html.erb
 <div class="container">
  <div class="row">
    <form class="form-signin" style='z-index:50; position: relative;'>
      <h2 class="form-signin-heading" style="color:#000; background-color:rgba(255, 204, 68, 0.5)">
        <i class="fa fa-money"> </i><b> HipMoney</b><br>
        <span style="text-transform: lowercase; font-size: 10px;">Your personal finance dashboard</span></h2>

      <div class="login-wrap form-signin-heading">
        <center>
        <%= link_to 'Login with <i class="fa fa-google-plus"></i>'.html_safe, "/auth/google_oauth2"%>
      </center>
      </div>
    </form>
  </div>
</div>
<div class="video">
</div>

app/views/home/show.html.erb
<div class='row'>
  <div class="stocktwits"><%= render 'partials/sidebar' %></div>
  <%= render 'partials/stock_list' %>
  <%= render 'partials/stockcharts' %>
  <%= render 'partials/bitcoin' %>
<!--   <div class="portfolio"><%#= render 'partials/portfolio' %></div>
</div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HipMoney</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.2/underscore-min.js"></script>

    
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag %>
    <script src="http://cdn.jsdelivr.net/jquery.knob/1.2.9/jquery.knob.min.js"></script>
  </head>

<body>
  <section id="container" class="open-right-panel">
  <%if current_user%>
    <%= render 'partials/navbar' %>
  <%end%>
  <section id='main-content'>
    <section class='wrapper'>
      <%= yield %>
    </section>
  </section>
</section>

</body>

</html>

app/views/partials/_bitcoin.html.erb
<div class="col-md-3">
    <div class="profile-nav alt">
        <section class="panel text-center">
            <div class="user-heading alt wdgt-row bitcoin">
                <i class="fa fa-btc fa-4"></i>
            </div>

            <div class="panel-body">
                <div class="wdgt-value">
                    <h2 class="bit-count">$295</h2>
                    <p>Current Bitcoin Value</p>
                </div>
            </div>

        </section>
    </div>
</div>

app/views/partials/_bitcointracker.html.erb
<div class="col-md-8">
<section class="panel">
<div id="btc-quote">
</div>
<div class= "hide"></div>
<script type="text/javascript" src="//cdn-gh.firebase.com/btcquote/embed.js"></script></section></div>

app/views/partials/_navbar.html.erb
<!--header start-->
<header class="header fixed-top clearfix merge-header">
<!--logo start-->
  <div class="brand">
      <a href="index.html" class="logo">
         <!--  <img src="images/logo.png" alt=""> -->
         <h2>HIP<b>MONEY</b></h2>
      </a>
  </div>
      <!--logo end-->
  <div class="top-nav clearfix">

      <div class="top-nav clearfix">
      <!--search & user info start-->
        <dv class = "countdown"></div>
        <ul class="nav pull-right top-menu">

          <!-- user login dropdown start-->
          <li class="dropdown">
            <% if current_user%>
              <%= image_tag current_user.profile_pic %>
              <span class="username"><b> <%= current_user.name %> </b></span>
              <span><%= link_to '<i class="fa fa-sign-out"></i>'.html_safe, signout_path %></span>
              <% else %>
                <%= link_to '<img src="http://icons.iconarchive.com/icons/danleech/simple/1024/google-icon.png"><span class="username">  Sign in with Google</span>'.html_safe, "/auth/google_oauth2", class: 'dropdown-toggle'%>
            <% end %>

          </li>
          <!-- user login dropdown end -->
      </ul>
      <!--search & user info end-->
  </div>
  </div>
</header>
<!--header end-->

app/views/partials/_piechart.html.erb
<!-- <div class="col-sm-6">
    <section class="panel">
        <header class="panel-heading">
            Pie Chart
        <span class="tools pull-right">
            <a href="javascript:;" class="fa fa-chevron-down"></a>
            <a href="javascript:;" class="fa fa-cog"></a>
            <a href="javascript:;" class="fa fa-times"></a>
         </span>
        </header>
        <div class="panel-body">
            <div id="pie-chart" class="pie-chart">
                <div id="pie-chartContainer" style="width: 100%; height: 400px; text-align: left; padding: 0px; position: relative;">
                    <canvas class="flot-base" width="473" height="400" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 473px; height: 400px;"></canvas>
                    <canvas class="flot-overlay" width="473" height="400" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 473px; height: 400px;"></canvas>
                    <div class="legend">
                        <div style="position: absolute; width: 83px; height: 54px; top: 5px; right: 5px; opacity: 0.85; background-color: rgb(255, 255, 255);"> </div>
                        <table style="position:absolute;top:5px;right:5px;;font-size:smaller;color:#545454">
                            <tbody>
                                <tr>
                                    <td class="legendColorBox">
                                        <div style="border:1px solid #ccc;padding:1px">
                                            <div style="width:4px;height:0;border:5px solid rgb(121,209,207);overflow:hidden"></div>
                                        </div>
                                    </td>
                                    <td class="legendLabel">Paid Signup</td>
                                </tr>
                                <tr>
                                    <td class="legendColorBox">
                                        <div style="border:1px solid #ccc;padding:1px">
                                            <div style="width:4px;height:0;border:5px solid rgb(217,221,129);overflow:hidden"></div>
                                        </div>
                                    </td>
                                    <td class="legendLabel">Free Signup</td>
                                </tr>
                                <tr>
                                    <td class="legendColorBox">
                                        <div style="border:1px solid #ccc;padding:1px">
                                            <div style="width:4px;height:0;border:5px solid rgb(230,122,119);overflow:hidden"></div>
                                        </div>
                                    </td>
                                    <td class="legendLabel">Guest Signup</td></tr></tbody></table></div>
                                </div>
                            </div>
                        </div>
                    </section>
</div> -->

app/views/partials/_portfolio.html.erb
<div class="col-md-5">
    <div class="profile-nav alt">
        <section class="panel">
            <div class="panel-heading">
              <span class="title">MY PORTFOLIO</span>
              <div class="pull-right">
                <a href="#" class="btn stat-btn" data-toggle="tab" id="portfolio-edit"><i class="fa fa-edit"></i></a>
              </div>
            </div>
                <section class="panel">
                    <div class="panel-body">
                        <section id="flip-scroll">
                            <table class="table table-bordered table-striped table-condensed cf">
                                <thead class="cf">
                                <tr>
                                    <th>Ticker</th>
                                    <th>Buy Date</th>
                                    <th>Buy Price</th>
                                    <th>Shares</th>
                                    <th>P/L</th>
                                </tr>
                                </thead>
                                <tbody>
                                <% current_user.portfolio_show.each do |stock| %>
                                  <tr>
                                      <td><%= t = Stock.find(stock.stock_id).ticker %></td>
                                      <td><%= stock.purchase_date %></td>
                                      <td class="numeric">$<%= stock.purchase_price %></td>
                                      <td class="numeric"><%= stock.shares %></td>
                                      <td class="numeric"></td>
                                  </tr>
                                <% end %>
                                  <tr class="sum">
                                    <td><b>TOTAL</b></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td class="sum"></td>
                                  </tr>
                              </tbody>

                            </table>
                        </section>
                </div>
        </section>
    </div>
</div>

app/views/partials/_portfolioEdit.html.erb
<div class="col-md-5">
    <div class="profile-nav alt">
        <section class="panel">
            <div class="panel-heading">
              <span class="title">MY PORTFOLIO</span>
              <div class="pull-right"><%= link_to '<i class="fa fa-edit"></i>'.html_safe, '#', :class => "portfolio-show" %></div>
            </div>
                <section class="panel">
                    <div class="panel-body">
                        <section id="flip-scroll">
                            <table class="table table-bordered table-striped table-condensed cf">
                                <thead class="cf">
                                <tr>
                                    <th>Ticker</th>
                                    <th>Buy Date</th>
                                    <th>Buy Price</th>
                                    <th>Shares</th>
                                </tr>
                                </thead>
                                <tbody>
                                 <form role="form">
                                  <% current_user.portfolio_show.each do |stock| %>
                                    <tr>
                                        <td><%= Stock.find(stock.stock_id).ticker %></td>
                                        <td><input type="date" class="form-control" value="<%= stock.purchase_date %>"></td>
                                        <td class="numeric"><input type="text" class="form-control" value="<%= stock.purchase_price %>"></td>
                                        <td class="numeric"><input type="text" class="form-control" value="<%= stock.shares %>"></td>
                                    </tr>
                                  <% end %>
                                  <tr class="edit-button-tr">
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td class="edit-button-td"><button type="submit" class="btn btn-info">Submit</button></td>
                                  </tr>
                                </form>
                              </tbody>
                            </table>
                        </section>
                </div>
        </section>
    </div>
</div>

app/views/partials/_searchbox.html.erb
<div id='search_box'>
	<%= form_for @stock, url: stock_path, remote: true do |f| %>
		<%= f.text_field :name, :placeholder=>"Add a stock to your watchlist" %>
		<%= f.submit "+" %>
	<% end %>
</div>
<div id="watchlist"></div>

app/views/partials/_sidebar.html.erb
<!--right sidebar start-->
<div class="right-sidebar open-right-bar">
<div class="right-stat-bar">
  <ul class="right-side-accordion">
  <li>
      <a href="#" class="head widget-head yellow-bg active clearfix">
          <span class="pull-left sbtext"><b>StockTwits</b> Feed</span>
            <%= image_tag "stocktwits_logo.png" %>
      </a>
    </li>
  </ul>
<div id="st_scroll">
    <ul>
        <li>
          <% if current_user.stocks %>
            <% info = current_user.stocktwits_feed %>
                <% info.each do |i| %>
                  <div class="prog-row">
                      <div class="user-thumb">
                        <%= image_tag i[:avatar] %>
                      </div>
                      <div class="user-details">
                        <h4><b><%= link_to i[:user], "http://www.stocktwits.com/#{i[:user]}", :target => "_blank" %> said: </b> <%= i[:body]%></h4>
                        <p>
                          <%= i[:time] %>
                        </p>
                      </div>
                  </div>
                <% end %>
            <% else %>
            <p>
              Looks like you haven't added any stocks to your watchlist!
            </p>
            <% end %>
      </li>
  </ul>
</div>
</div>
</div>
<!--right sidebar end-->

app/views/partials/_smallwidgets.html.erb
<section class="wrapper">
<!--mini statistics start-->
  <div class="col-md-3">
    <section class="panel">
      <div class="panel-body">
        <div class="top-stats-panel">
          <div class="monthly-stats pink">
            <div class="clearfix">
              <img src="images/chat-user-thumb.png" alt="logo">
              <h4 class="pull-right">APPL</h4>
            </div>
                    <!-- Tab panes -->
          </div>
          <div class="daily-visit">
            <div id="daily-visit-chart" style="width: 100%; height: 100px; display: block; padding: 0px; position: relative;">

              <canvas class="flot-base" width="160" height="100">
              </canvas>
              <div class="flot-text" style="position: absolute; top: 0px; left: 0px; bottom: 0px; right: 0px; font-size: smaller; color: rgb(84, 84, 84);">
                <div class="flot-x-axis flot-x1-axis xAxis x1Axis">
                  <div>
                    2
                  </div>
                  <div >
                    4
                  </div>
                  <div>
                    6</div><div>8</div><div>10</div></div><div class="flot-y-axis flot-y1-axis yAxis y1Axis"><div>0</div><div>50</div><div>100</div></div></div><canvas class="flot-overlay" width="160" height="100"></canvas></div>
              </div>
            </div>
            <div class="daily-visit">
              <ul class="chart-meta clearfix">
                <li class="pull-left visit-chart-value">3233</li>
                <li class="pull-right visit-chart-title"><i class="fa fa-arrow-up"></i> 15%</li>
              </ul>
            </div>
          </div>
    </section>
  </div>
</section>

app/views/partials/_stock_list.html.erb
<div class="col-md-4">
                        <!--widget start-->
  <aside class="profile-nav alt">
    <header class="panel-heading"><span class='stock title'>My Stock Watchlist</span>
      <input id='input'>
        <span class="tools pull-right">
            <a href="javascript:;" class="fa fa-plus"></a>
        </span>
      </header>
      <section class="panel">
        <div id='results'></div>
          <div class="user-heading alt gray-bg">
              <a >
                 <div class='stock-logo'>
                  <img alt="" src=<%= current_user.stocks[-1].logo || 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcREagc_JNfLZ2y2iNotwwik1uduhiCB9HRD0QPVECZK0uqtutIAUA'%>>
                </div>
              </a>
              <h2><%= current_user.stocks[-1].ticker %></h2>
              <p><%= current_user.stocks[-1].name %></p>
          </div>
        <div class="stock-body stocklist">
        <ul class="nav nav-pills nav-stacked">

        <% quotes = current_user.get_price %>
        <% rs = current_user.stocks.reverse %>
        <% rs.each_index do |i| %>
          <li data-name=<%= rs[i].name %> data-ticker=<%= rs[i].ticker %> data-url=<%= rs[i].logo || 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcREagc_JNfLZ2y2iNotwwik1uduhiCB9HRD0QPVECZK0uqtutIAUA' %> data-id=<%= rs[i].id %>>
            <span><a>
              <%= rs[i].ticker %>
            </a></span>
            <span class="badge label-success pull-right r-activity">$<%= quotes[i].ask %></span>&nbsp;
            <span><%= link_to "", stocks_path(rs[i]), method: :delete, remote: true, class: "fa fa-minus-circle red" %></span>
          </li>
            <% end %>
          </ul>
        </div>
      </section>
  </aside>
  <!--widget end-->

</div>

app/views/partials/_stockcharts.html.erb
<div class="col-md-8">
<section class="panel">
   <header class="panel-heading">
    <span class="title">STOCK PRICE CHART</span>
    <div class="btn-group pull-right stat-tab">
                <a href="#line-chart" class="btn stat-btn" data-toggle="tab"><i class="fa fa-clock-o"></i></a>
                <a href="#bar-chart" class="btn stat-btn active" data-toggle="tab"><i class="fa fa-bar-chart-o"></i></a>
            </div> <!--<span class="tools pull-right">
            <a href="javascript:;" class="fa fa-chevron-down"></a>
            <a href="javascript:;" class="fa fa-cog"></a>
            <a href="javascript:;" class="fa fa-times"></a>
          </span>-->
    </header>
    <div class="panel-body">
      <div id="stockchart"></div>
    </div>
</section>
</div>
        <script src="http://code.highcharts.com/stock/highstock.js"></script>
        <script src="http://code.highcharts.com/stock/modules/exporting.js"></script>

app/views/partials/_stocktwitfeed.html.erb
<div class="pstfeed">
  <% current_user.stocks.each do |stock| %>
        <div class="row tiles-container">
            <div class="m-l-10 ">
              <div class="tiles grey p-t-15 p-b-15 p-l-25 ">
                <h5 class="text-black semi-bold">THE LATEST
                <i>from</i>
                <b>StockTwits</b>
                || $<%= stock.ticker %>
                </h5>
              </div>
          <% info = stock.stocktwits_feed %>
            <% info.each do |i| %>
              <div class="tiles white ">
                <div class="p-t-20 p-b-15 b-b b-grey">
                  <div class="post overlap-left-10">
                    <div class="user-profile-pic-wrapper">
                      <div class="user-profile-pic-2x white-border">
        					<img width="45" height="45" src="<%= i[:user_pic]%>" data-src="assets/img/profiles/avatar.jpg" data-src-retina="assets/img/profiles/avatar2x.jpg" alt="">
        					</div>
                    </div>
                    <div class="info-wrapper small-width inline">
                      <div class="info text-black ">
                        <p><b><%= i[:user] %> said: </b> <%= i[:body]%></p>
                        <p class="muted small-text"><%= i[:time] %></p>
                      </div>
                      <div class="clearfix"></div>
                    </div>
                    <div class="inline pull-right">
                      <div class="tiles text-white p-t-5 p-l-5 p-b-5 p-r-5 inline"> <i class="fa fa-heart-o fa-lg"></i> </div>
                      <div class="tiles white p-t-5 p-l-5 p-b-5 p-r-5 inline"> <i class="fa fa-comment-o fa-lg"></i> </div>
                    </div>
                    <div class="clearfix"></div>
                  </div>
                </div>
              </div>
              <% end %>
              <div class="tiles grey p-t-5 p-b-5 ">
               <p class="text-center"> <a href="javascript:;" class="text-black semi-bold  small-text">Load More</a></p>
              </div>
            </div>
          </div>
          <Br>
    <% end %>
</div>

app/views/partials/_watchlist.html.erb
<div class="pwatchlist">
 <div class="row tiles-container tiles white"  >
   <div class="col-md-5 no-padding col-sm-5">
              <div class="p-l-15 p-r-15 p-b-10 p-t-10 b-b b-grey">
                <h3 class="text-error bold inline no-margin">Watchlist</h3>
                <div class="pull-right">
                  <%= Time.new.strftime("%m/%d/%Y %H:%M%p")  %>
                  <a href="javscript:;" class="remove">X</a>
                </div>
              </div>
              <% current_user.stocks.each do |stock| %>
                <div class="scroller" data-height="410px" data-always-visible="1">
                  <div class="p-l-15 p-r-15 p-b-10 p-t-10 b-b b-grey">
                    <div class="pull-left">
                      <p class="small-text"><%= stock.ticker %></p>
                    </div>
                    <div class="pull-right">
                      <p class="small-text"><%= stock.name %></p>
                    </div>
                    <div class="clearfix"></div>
                    <div class="pull-left">
                      <h4 class="semi-bold">99.78</h4>
                    </div>
                    <div class="pull-right" style="line-height: 27px;"> <span class="label label-important" style="vertical-align: bottom;">-318.2</span>
                      or <span class="label label-success" style="vertical-align: bottom;">+318.2</span>
                    </div>
                    <div class="clearfix"></div>
                  </div>
                </div>
              <% end %>
    </div>
  </div>
</div>

app/views/stocks/destroy.js.erb
$('li[data-id="<%= @stock.id %>"]').remove();	